server {
    listen 5000;
    server_name _;

    location = / {
        return 302 /gold-price-alert/;
    }

    location = /gold-price-alert {
        return 301 /gold-price-alert/;
    }

    location = /gold-price-alert/api {
        return 301 /gold-price-alert/api/;
    }

    location ^~ /gold-price-alert/api/ {
        proxy_pass http://10.140.0.2;
        proxy_http_version 1.1;
        proxy_set_header Host 10.140.0.2;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /gold-price-alert/ {
        alias /usr/share/nginx/html/;
        try_files $uri $uri/ /gold-price-alert/index.html;
    }

    location / {
        return 404;
    }
}
